-- auto Generated on 2019-08-02 16:44:50 
-- DROP TABLE IF EXISTS `oms_order`; 
CREATE TABLE oms_order(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `member_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'memberId',
    `coupon_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'couponId',
    `order_sn` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'orderSn',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `member_username` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'memberUsername',
    `total_amount` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'totalAmount',
    `pay_amount` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'payAmount',
    `freight_amount` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'freightAmount',
    `promotion_amount` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'promotionAmount',
    `integration_amount` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'integrationAmount',
    `coupon_amount` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'couponAmount',
    `discount_amount` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'discountAmount',
    `pay_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'payType',
    `source_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'sourceType',
    `status` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'status',
    `order_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'orderType',
    `delivery_company` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'deliveryCompany',
    `delivery_sn` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'deliverySn',
    `auto_config_day` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'autoConfigDay',
    `integration` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'integration',
    `growth` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'growth',
    `promotion_info` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'promotionInfo',
    `bill_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'billType',
    `bill_header` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'billHeader',
    `bill_content` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'billContent',
    `bill_receiver_phone` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'bill_receiverPhone',
    `bill_receiver_email` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'billReceiverEmail',
    `receiver_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'receiverName',
    `receiver_phone` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'receiverPhone',
    `receiver_post_code` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'receiverPostCode',
    `receiver_province` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'receiverProvince',
    `receiver_city` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'receiverCity',
    `receiver_region` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'receiverRegion',
    `receiver_detail_address` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'receiverDetailAddress',
    `note` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'note',
    `confirm_status` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'confirmStatus',
    `delete_status` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'deleteStatus',
    `use_integration` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'useIntegration',
    `payment_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'paymentTime',
    `delivery_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'deliveryTime',
    `receive_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'receiveTime',
    `comment_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'commentTime',
    `modify_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'modifyTime',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'oms_order';
